### PR TITLE
feat(no-empty-component-block): support auto fix

### LINKED ISSUE #2564: autofix for vue/no-empty-component-block
**What rule do you want to change?**
- Rule to change is vue/no-empty-component-block

**Does this change cause the rule to produce more or fewer warnings?**
- This change would not change the amount of errors/warnings

**How will the change be implemented? (New option, new default behavior, etc.)?**
- Preferably default behaviour

**Please provide some example code that this change will affect:**

```vue
<script setup lang="ts">
  defineProps<{...}>()
</script>

<template>
  <h1>My awesome title</h1>
</template>

<style scoped lang="postcss"></style>
```

**What does the rule currently do for this code?**
- Currently the rule marks the style tag as an error, but you would have to remove it manually

**What will the rule do after it's changed?**
- After change eslint will be able to remove the style tag with `pnpm eslint --fix`

**Additional context**

### PR DESCRIPTION
**Pull request by waynzh**
resolve #2564

~~Chose this approach is because I couldn't find a better way to handle reporting & fixing each `emptyBlock` within a for loop,  as removing the first block will affect the range of the second block😵‍💫.~~

UPDATE: support auto delete empty blocks

### CODE REVIEW

File: lib/rules/no-empty-component-block.js [hunk 1]
```diff
@@ -85,6 +99,29 @@ module.exports = {
...
           ) {
+            emptyBlocks.push(componentBlock)
+          }
+        }
+
+        if (emptyBlocks.length === 0) return
+
+        if (autofix) {
+          const firstEmptyBlock = emptyBlocks[0]
+          context.report({
```
Comment (ota-meshi) [inline lib/rules/no-empty-component-block.js:110]: I don't think the option changes the reported location.
They may be ignored by the `eslint-disable` directive, so I think it's necessary to report them one by one and auto fix them for each report.
Could you please change it?

**Review by ota-meshi — CHANGES_REQUESTED** [review]
Thank you for this PR!

File: lib/rules/no-empty-component-block.js (hunk 1 above)
Comment (ota-meshi) [reply lib/rules/no-empty-component-block.js:110]: > Chose this approach is because I couldn't find a better way to handle reporting & fixing each emptyBlock within a for loop, as removing the first block will affect the range of the second block😵‍💫.

I think a good way to test removing them in one go is to have some whitespace between each block.
Adjacent autofixes will not be fixed at the same time to avoid conflicts.

Comment (waynzh) [reply lib/rules/no-empty-component-block.js:110]: I'll look into it later, thanks.

File: lib/rules/no-empty-component-block.js [hunk 2]
```diff
@@ -85,16 +99,29 @@ module.exports = {
...
+            messageId: 'unexpected',
+            data: {
+              blockName: componentBlock.name
+            },
+            fix: autofix
+              ? function* (fixer) {
+                  for (const componentBlock of emptyBlocks) {
+                    yield fixer.remove(componentBlock)
+                  }
+                }
```
Comment (ota-meshi) [inline lib/rules/no-empty-component-block.js:121]: Could you please change it to auto-fix only reported block?

```suggestion
              ? (fixer) => fixer.remove(componentBlock)
```

File: docs/rules/no-empty-component-block.md [hunk 3]
```diff
@@ -62,7 +64,15 @@ p {
 
 ## :wrench: Options
 
-Nothing.
+```json
+{
+  "vue/no-duplicate-attributes": ["error", {
```
Comment (FloEdelmann) [inline docs/rules/no-empty-component-block.md:69]:
```suggestion
  "vue/no-empty-component-block": ["error", {
```

File: docs/rules/no-empty-component-block.md [hunk 4]
```diff
@@ -62,7 +64,15 @@ p {
...
+    "autofix": false,
+  }]
+}
+```
+
+- `"autofix"` ... If `true`, enable autofix. (Default: `false`)
```
Comment (FloEdelmann) [inline docs/rules/no-empty-component-block.md:75]: Why does this have to be an option? I think always adding the autofix would be fine and would reduce the complexity a bit.

**Review by FloEdelmann — CHANGES_REQUESTED** [review]

File: docs/rules/no-empty-component-block.md (hunk 4 above)
Comment (waynzh) [reply docs/rules/no-empty-component-block.md:75]: I treated it as providing an auto-fix feature, and upgrading the package wouldn't change the current code. Of course, I think it's also reasonable to directly fix it in the next minor version.

Comment (ota-meshi) [reply docs/rules/no-empty-component-block.md:75]: I think it's okay if there are no options.
My only concern is that if we have autofix on save enabled in our editor, it will be removed if we temporarily save while writing code.
But other than that, I think it's better to have autofix enabled all the time. If it gets removed, you can probably undo it with Ctrl(Option)+Z.

Comment (waynzh) [reply docs/rules/no-empty-component-block.md:75]: I'll update the doc and tests later

File: lib/rules/no-empty-component-block.js [hunk 5]
```diff
@@ -70,6 +70,9 @@ module.exports = {
 
     return {
       Program() {
+        /** @type {VElement[]} */
+        const emptyBlocks = []
```
Comment (FloEdelmann) [inline lib/rules/no-empty-component-block.js:74]: I think this array can be removed again; better report the errors directly when iterating `componentBlocks`.

Comment (FloEdelmann) [reply lib/rules/no-empty-component-block.js]: No worries :slightly_smiling_face:
