### PR TITLE
fix(no-v-html): add CallExpression support to ignorePattern option

### LINKED ISSUE #2949: vue/no-v-html ignorePattern regex escaping causes different behavior in VS Code vs CLI
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 9.39.1
- **eslint-plugin-vue version:** 10.5.1
- **Vue version:** 3.5.22
- **Node version:** 24.3.0
- **Operating System:** macOS

**Please show your full configuration:**

```js
import js from "@eslint/js";
import ts from "typescript-eslint";
import prettierConfig from "eslint-plugin-prettier/recommended";
import globals from "globals";
import vue from "eslint-plugin-vue";
import vueA11y from "eslint-plugin-vuejs-accessibility";
import storybook from "eslint-plugin-storybook";

const ignoredFiles = [];

export default [
  { ignores: ignoredFiles },
  js.configs.recommended,
  ...ts.configs.recommendedTypeChecked,
  ...vue.configs["flat/recommended"],
  ...vueA11y.configs["flat/recommended"],
  ...storybook.configs["flat/recommended"],
  prettierConfig,
  {
    languageOptions: {
      parserOptions: {
        ecmaVersion: 2020,
        parser: ts.parser,
        sourceType: "module",
        project: ["./tsconfig.json"],
        extraFileExtensions: [".vue"],
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
  },
  {
    rules: {
      "prettier/prettier": "error",
      "no-console": "error",
      eqeqeq: "error",
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/no-import-type-side-effects": "error",
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      "vue/no-v-html": [
        "error",
        {
          ignorePattern: "/^\$sanitize\(/",
        },
      ],
    },
  },
];
```

**What did you do?**

```vue
<template>
  <div v-html="$sanitize(contentHtml)"></div>
</template>
```

I configured the `vue/no-v-html` rule with an `ignorePattern` option to ignore v-html usage when the content is sanitized using `$sanitize()` function.

**What did you expect to happen?**

The `ignorePattern` option should work consistently both in VS Code and when running ESLint via CLI. When using the pattern `/^\\$sanitize\\(/`, it should properly ignore the v-html usage for expressions starting with `$sanitize(` without causing syntax errors.

**What actually happened?**

There are two different behaviors depending on how the regular expression is written:

1. **With pattern `/^\$sanitize\(/`:**
   - VS Code shows no lint errors (works correctly in IDE)
   - CLI execution fails with syntax error: `SyntaxError: Error while loading rule 'vue/no-v-html': Invalid regular expression: //^$sanitize(//u: Unterminated group`

2. **With pattern `/^\\$sanitize\\(/`:**
   - CLI execution works without errors
   - VS Code still shows lint errors for the ignored pattern (ignorePattern not working in IDE)

The `ignorePattern` option behaves inconsistently between VS Code extension and CLI execution, and proper escaping of the regular expression seems to cause different issues in different environments.

**Repository to reproduce this issue**

https://github.com/kzhrk/eslint-plugin-vue-2949

### PR DESCRIPTION
**Pull request by kzhrk**
Closes #2949

Extends the `ignorePattern` option to support CallExpression (function call)
patterns like `$sanitize(test)`, previously only supporting simple identifiers.

This allows users to ignore sanitized HTML expressions using patterns such as
`^\$sanitize\(`.

### CODE REVIEW

File: tests/lib/rules/no-v-html.js [hunk 1]
```diff
@@ -33,6 +33,11 @@ ruleTester.run('no-v-html', rule, {
       filename: 'test.vue',
       code: '<template><div v-html="htmlKnownToBeSafe"></div></template>',
       options: [{ ignorePattern: '^html' }]
+    },
+    {
+      filename: 'test.vue',
+      code: '<template><div v-html="$sanitize(test)"></div></template>',
+      options: [{ ignorePattern: String.raw`^\$sanitize\(` }]
```
Comment (FloEdelmann) [inline tests/lib/rules/no-v-html.js:40]: Please add another test with the ignore pattern `"/^\\$sanitize\\(/"` that was mentioned in the original issue.

File: .changeset/add-callexpression-support.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+'eslint-plugin-vue': patch
+---
+
+fix(no-v-html): add CallExpression support to ignorePattern option (#2949)
```
Comment (FloEdelmann) [inline .changeset/add-callexpression-support.md]:
```suggestion
Fixed `vue/no-v-html` rule to allow ignoring call expressions
```

**Review by FloEdelmann — CHANGES_REQUESTED** [review]
Thanks for looking into it and fixing the core issue! This looks really good 🙂 

I just have two minor suggestion.

File: tests/lib/rules/no-v-html.js (hunk 1 above)
Comment (FloEdelmann) [reply tests/lib/rules/no-v-html.js:40]: Nevermind, this option works differently, so your test case is fine.

File: lib/rules/no-v-html.js [hunk 3]
```diff
@@ -36,15 +36,37 @@ module.exports = {
...
+
+      // For other expression types (e.g., CallExpression), get the full text
+      const expressionText = sourceCode.getText(expression)
+      return ignoreRegEx.test(expressionText)
+    }
+
     return utils.defineTemplateBodyVisitor(context, {
       /** @param {VDirective} node */
       "VAttribute[directive=true][key.name.name='html']"(node) {
+        const sourceCode = context.sourceCode
```
[the remark this answers is not in the document]
Comment (FloEdelmann) [reply lib/rules/no-v-html.js]: That is indeed correct; we use the `getSourceCode` function as a shim to support older versions of ESLint.

**Review by FloEdelmann — APPROVED** [review]

**Comment by kzhrk** [comment]
@FloEdelmann 
Thanks for the fixes and the quick follow-up commits!😊
