### PR TITLE
docs: fix build on windows

### LINKED ISSUE #2492: `TypeError: require is not a function` when running `npm run docs:watch` locally
I've tried to contribute to the documentation, but when I run `npm run docs:watch`, I only get a blank page with the following error:

```
Uncaught TypeError: require is not a function
    at index.js:9:9
```

image

What I did:
- installed dependencies with `npm install`
- ran `npm run docs:watch`

I've also tried to build the library with `npm run tsc`, but got the following error:

```
lib/rules/order-in-components.js:265:25 - error TS7006: Parameter 'fixer' implicitly has an 'any' type.

265     function* handleFix(fixer, propertyNode, unorderedPropertyNode) {
                            ~~~~~


Found 1 error in lib/rules/order-in-components.js:265
```

I'm on:
- Windows 10
- Node v20.15.0

### PR DESCRIPTION
**Pull request by Lehoczky**
Resolves #2492 

This PR uses [pathe](https://www.npmjs.com/package/pathe) instead of the built-in path module from Node.js to handle the different file separators between Windows and other operating systems.

I tested it, and works, it's only a draft because I'm not sure you want to add another dependency to the project, even if it is only a dev dependency.

### CODE REVIEW

File: lib/rules/order-in-components.js [hunk 1]
```diff
@@ -259,6 +259,7 @@ module.exports = {
     }
 
     /**
+     * @param {RuleFixer} fixer
```
Comment (Lehoczky) [inline lib/rules/order-in-components.js:262]: This is not needed, It just fixes the tsc error on the main branch. This was implicitly any before.

**Review by ota-meshi — APPROVED** [review]
Thanks for this PR!
Looks good to me. If you think it's OK to merge, please remove the draft mark.
