### PR TITLE
Fix false positives for `v-bind="obj"` with `v-model` in `vue/attributes-order` rule

### LINKED ISSUE #1767: vue/attributes-order doesn't order v-bind correct
**Checklist**

-  I have tried restarting my IDE and the issue persists.
-  I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **Vue version":** 3.2.27
- **ESLint version:** 8.7.0
- **eslint-plugin-vue version:**  8.3.0
- **Node version:** 16.13.0
- **Operating System:**  macOS Monterey 12.1

**Please show your full configuration:**

```json5
extends: [
        'eslint:recommended',
        'plugin:vue/vue3-essential',
        'plugin:vue/vue3-strongly-recommended',
        'plugin:vue/vue3-recommended',
],
rules: {
        'vue/attributes-order': 2,
}
```

**What did you do?**	

```vue
<base-menu
        v-model:placement="placement"
        v-bind="menuProps"
        :value="focused"
        :class="className"
        @click:outside="hideOptions"
    />
```

**What did you expect to happen?**
no warning on console

**What actually happened?**

```
Module Warning (from ./node_modules/vue-loader/dist/templateLoader.js):
(Emitted value instead of an instance of Error) (deprecation COMPILER_V_BIND_OBJECT_ORDER) v-bind="obj" usage is now order sensitive and behaves like JavaScript object spread: it will now overwrite an existing non-mergeable attribute that appears before v-bind in the case of conflict. To retain 2.x behavior, move v-bind to make it the first attribute. You can also suppress this warning if the usage is intended.
  Details: https://v3.vuejs.org/guide/migration/v-bind.html
2  |      <base-menu
3  |          v-model:placement="placement"
4  |          v-bind="menuProps"
   |          ^^^^^^^^^^^^^^^^^^
5  |          :value="focused"
6  |          :class="className"

```

**What did you do?**	

```vue
<base-menu
        v-bind="menuProps"
        v-model:placement="placement"
        :value="focused"
        :class="className"
        @click:outside="hideOptions"
    />
```

**What did you expect to happen?**
no warning on console

**What actually happened?**

```
ERROR in component.vue:4:9
vue/attributes-order: Attribute "v-model:placement" should go before "v-bind".
    2 |     <base-menu
    3 |         v-bind="menuProps"
    4 |         v-model:placement="placement"

```

**Repository to reproduce this issue**

### PR DESCRIPTION
**Pull request by ota-meshi**
fixes #1767

### CODE REVIEW

File: lib/rules/attributes-order.js [hunk 1]
```diff
@@ -298,11 +306,13 @@ function create(context) {
...
-        (isVAttributeOrVBind(attributes[index - 1]) ||
-          isVAttributeOrVBind(attributes[index + 1]))
+        (isVAttributeOrVBindOrVModel(attributes[index - 1]) ||
+          isVAttributeOrVBindOrVModel(attributes[index + 1]))
       ) {
-        // In Vue 3, ignore the `v-bind:foo=" ... "` and `v-bind ="object"` syntax
-        // as they behave differently if you change the order.
+        // In Vue 3, ignore `v-bind ="object"`, which is
+        // a pair of `v-bind:foo="..."` and `v-bind ="object"` and
+        // a pair of `v-model="..."` and `v-bind ="object"`,
```
Comment (FloEdelmann) [inline lib/rules/attributes-order.js:314]:
```suggestion
        // In Vue 3, ignore `v-bind="object"`, which is
        // a pair of `v-bind:foo="..."` and `v-bind="object"` and
        // a pair of `v-model="..."` and `v-bind="object"`,
```

File: lib/rules/attributes-order.js [hunk 2]
```diff
@@ -330,14 +340,14 @@ function create(context) {
       if (isVBindObject(node)) {
         // node is `v-bind ="object"` syntax
 
-        // In Vue 3, if change the order of `v-bind:foo=" ... "` and `v-bind ="object"`,
+        // In Vue 3, if change the order of `v-bind:foo="..."`, `v-model="..."` and `v-bind ="object"`,
```
Comment (FloEdelmann) [inline lib/rules/attributes-order.js:343]:
```suggestion
        // In Vue 3, if change the order of `v-bind:foo="..."`, `v-model="..."` and `v-bind="object"`,
```

File: tests/lib/rules/attributes-order.js [hunk 3]
```diff
@@ -1246,6 +1282,50 @@ tester.run('attributes-order', rule, {
...
+      <template>
+        <div
+          v-if="x"
+          v-bind="b"
+          v-bind:id="a"
+          v-model="c">
+        </div>
+      </template>`,
+      errors: ['Attribute "v-bind:id" should go before "v-model".']
+    },
```
Comment (FloEdelmann) [inline tests/lib/rules/attributes-order.js:1328]: Will this create false positives in existing Vue 2 code? There, the order `v-if, v-model, v-bind, v-bind:id` would be perfectly fine.

**Review by FloEdelmann — CHANGES_REQUESTED** [review]

File: lib/rules/attributes-order.js (hunk 2 above)
Comment (ota-meshi) [reply lib/rules/attributes-order.js]: Thank you!

File: tests/lib/rules/attributes-order.js (hunk 3 above)
Comment (ota-meshi) [reply tests/lib/rules/attributes-order.js:1328]: I don't think there are any false positives because the `id` must be before the `v-model`.

https://vuejs.org/v2/style-guide/#Element-attribute-order-recommended

Comment (FloEdelmann) [reply tests/lib/rules/attributes-order.js:1328]: Oh, indeed.

Comment (FloEdelmann) [reply tests/lib/rules/attributes-order.js:1328]: Oh, indeed.

**Review by FloEdelmann — APPROVED** [review]
