### PR TITLE
[Fixes #315] Report missing prop types only for assigned arrays and objects

### LINKED ISSUE #315: False positive in rule "vue/require-prop-types"
**Tell us about your environment**

* **ESLint Version:** 4.14.0
* **eslint-plugin-vue Version:** 4.0.0
* **Node Version:** 8.5.0

**Please show your full configuration:**
```js
// basic configuration
module.exports = {
  root: true,
  extends: [
    'airbnb-base',
    'plugin:vue/recommended',
  ],
  parserOptions: {
    parser: 'babel-eslint'
  },
  plugins: ['vue']
}
```

**What did you do? Please include the actual source code causing the issue.**

```js
import props from './Foo.props';

// @vue/component
export default {
  name: 'Foo',
  props,
  render: h => h('div', 'foo'),
};
```

**What did you expect to happen?**
Should not raise require-prop-types error

**What actually happened? Please include the actual, raw output from ESLint.**
Setting props in a component that are defined outside of it raises the error:

```
C:\dev\foobar\src\app.js
  6:3   error  Props should at least define their types vue/require-prop-types

✖ 1 problem (1 error, 0 warnings)
```

### PR DESCRIPTION
**Pull request by michalsnik**
#315

### CODE REVIEW

File: tests/lib/rules/require-prop-types.js [hunk 1]
```diff
@@ -69,6 +69,24 @@ ruleTester.run('require-prop-types', rule, {
         }
       `,
       parserOptions: { ecmaVersion: 6, sourceType: 'module' }
+    },
+    {
+      filename: 'test.vue',
+      code: `
+        export default {
```
Comment (mysticatea) [inline tests/lib/rules/require-prop-types.js]: It's needed to enclose by `<script>` element.

Comment (michalsnik) [reply tests/lib/rules/require-prop-types.js]: Nope, it's not needed. It works good as is :) It's enough to put `export default {` and `.vue` filename :)

Comment (mysticatea) [reply tests/lib/rules/require-prop-types.js]: Oh, I got it. I had misunderstood that the tests are using `vue-eslint-parser`.
