### PR TITLE
fix(valid-define-options): Allow the use of simple constants

### LINKED ISSUE #2919: Support literal constant references in `vue/valid-define-options` rule
**What rule do you want to change?**valid-define-options

**Does this change cause the rule to produce more or fewer warnings?**
no

**How will the change be implemented? (New option, new default behavior, etc.)?**
Add option to ignoreVariables in valid-define-options

**Please provide some example code that this change will affect:**

before
```ts
const COMPONENT_NAME = 'ElForm'
defineOptions({
  name: COMPONENT_NAME, // ❌ ESLint: referencing locally declared variables
})
```
config:
```json
{
  "vue/valid-define-options": [
    "error",
    { "allowVariableNamePattern": "^[A-Z_]+$" }
  ]
}
```
after
```ts
const COMPONENT_NAME = 'ElForm'

defineOptions({
  name: COMPONENT_NAME, // ✅ allowed
})
```

“Because the COMPONENT_NAME variable will be used multiple times in the <script> block, but it will never change.”

**What does the rule currently do for this code?**

**What will the rule do after it's changed?**

**Additional context**

### PR DESCRIPTION
**Pull request by FrontEndDog**
Fixes #2919

### CODE REVIEW

File: lib/rules/valid-define-options.js [hunk 1]
```diff
@@ -89,12 +89,19 @@ module.exports = {
...
+                  if (utils.inRange(defineOptions.range, def.name)) return false
+                  if (
+                    def.type === 'Variable' &&
+                    def.parent.kind === 'const' &&
+                    def.node.init &&
+                    def.node.init.type === 'Literal'
+                  )
+                    return false
+                  return true
+                })
```
Comment (FloEdelmann) [inline lib/rules/valid-define-options.js]:
```suggestion
                variable.defs.every(
                  (def) =>
                    def.type !== 'ImportBinding' &&
                    utils.inRange(scriptSetup.range, def.name) &&
                    !utils.inRange(defineOptions.range, def.name) &&
                    !(
                      def.type === 'Variable' &&
                      def.parent.kind === 'const' &&
                      def.node.init &&
                      def.node.init.type === 'Literal'
                    )
                )
```

Comment (FrontEndDog) [reply lib/rules/valid-define-options.js]: @FloEdelmann Thanks for your review！I have already made the modifications.

**Comment by FrontEndDog** [comment]
I haven't changed to any other rules, I don't know why automated testing failed.

**Comment by FloEdelmann** [comment]
> I don't know why automated testing failed

That failure is indeed unrelated; I opened an issue about it:

* https://github.com/vuejs/vue-eslint-parser/issues/274

**Comment by FloEdelmann** [comment]
https://github.com/vuejs/vue-eslint-parser/issues/274 is now fixed, I updated your branch.

**Review by FloEdelmann — APPROVED** [review]
Thanks! 🙂
