### PR TITLE
Fix: `no-invalid-template-root` has false positive about empty templates (fixes #41)

### LINKED ISSUE #41: Suggestion: relax `invalid-template-root` for `v-if`
**Tell us about your environment**

* **ESLint Version:** 4.0.0
* **eslint-plugin-vue Version:** 3.1.2
* **Node Version:** 8.0.0

Conditionally empty template root can be acceptable. For example, in a list item component, if an item is empty/undefined, empty template root represents `skipping render`.  

The reason behind it is that we can encapsulate null check in the component, so we can pass empty value to the component.

vue-hackernews also employs such strategy.
https://github.com/vuejs/vue-hackernews-2.0/blob/master/src/components/Comment.vue#L2

```vue
<template>
  <li v-if="comment" class="comment">
  </li>
</template>
```

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #41.

This PR removes the warnings about empty templates.

### CODE REVIEW

File: tests/lib/rules/no-invalid-template-root.js [hunk 1]
```diff
@@ -50,16 +50,23 @@ tester.run('no-invalid-template-root', rule, {
...
       code: `<template>\n    <c1 v-if="1" />\n    <c2 v-else-if="1" />\n    <c3 v-else />\n</template>`
-    }
-  ],
-  invalid: [
+    },
     {
       filename: 'test.vue',
-      code: '<template>\n</template>',
-      errors: ['The template root requires exactly one element.']
+      code: '<template>\n</template>'
```
Comment (HerringtonDarkholme) [inline tests/lib/rules/no-invalid-template-root.js]: Empty template seems also bad since users can simply skip the template section. I would like to see exactly one element warning back.

Comment (HerringtonDarkholme) [inline tests/lib/rules/no-invalid-template-root.js]: I think template root should be empty only if it is an external template reference. 

Related: https://github.com/octref/vetur/issues/272

Comment (mysticatea) [inline tests/lib/rules/no-invalid-template-root.js]: @HerringtonDarkholme Could you know where the document about `<template src="foo.html">` is? [User guide](https://vuejs.org/v2/guide/single-file-components.html#What-About-Separation-of-Concerns) seems to not say about `<template src="foo.html">`.

Comment (HerringtonDarkholme) [inline tests/lib/rules/no-invalid-template-root.js]: It is listed in vue-loader's spec. http://vue-loader.vuejs.org/en/start/spec.html#src-imports

Comment (mysticatea) [inline tests/lib/rules/no-invalid-template-root.js]: @HerringtonDarkholme Thank you!

File: tests/lib/rules/no-invalid-template-root.js [hunk 2]
```diff
@@ -90,23 +102,23 @@ tester.run('no-invalid-template-root', rule, {
...
-      errors: ["The template root requires the next element which has 'v-else' directives if it has 'v-if' directives."]
+      code: '<template><template></template></template>',
+      errors: ["The template root disallows '<template>' elements."]
     },
     {
       filename: 'test.vue',
-      code: '<template><slot></slot></template>',
-      errors: ["The template root disallows '<slot>' elements."]
+      code: '<template src="foo.html">abc</template>',
+      errors: ["The template root which has 'src' attribute requires empty."]
```
Comment (michalsnik) [inline tests/lib/rules/no-invalid-template-root.js]: What do you think about amending this message to be: `The template root with 'src' attribute is required to be empty.`

File: docs/rules/no-invalid-template-root.md [hunk 3]
```diff
@@ -6,16 +6,21 @@ This rule checks whether every template root is valid.
 
 This rule reports the template root if the following cases:
```
Comment (michalsnik) [inline docs/rules/no-invalid-template-root.md]: I know it's out of the scope of this task, but if you're already on it maybe you could change `if` to `in`. We can also do a separate PR with copy updates though, so whatever..

**Comment by mysticatea** [comment]
Thank you for corrections!
