### PR TITLE
Fix false positive for unknown prop in `vue/no-undef-properties` rule

### LINKED ISSUE #2183: Vue 3.3 throws vue/no-undef-properties for types exported from external files
**Tell us about your environment**

- **ESLint version:** 8.40.0
- **eslint-plugin-vue version:** 9.13.0
- **Node version:** 18.16.0
- **Operating System:** MacOs 13.3.1

**Please show your full configuration:**

```json5
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'plugin:vue/vue3-essential',
    '@vue/airbnb',
    '@vue/typescript/recommended',
  ],
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-undef': 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'import/prefer-default-export': 'off',
    'import/extensions': 'off',
    'import/no-unresolved': 'off',
    'no-shadow': 'off',
    semi: 'off',
    'vue/no-undef-properties': 'warn',
  },
};

```

**What did you do?**	

```vue
<script setup lang="ts">
import {
  ref,
  watch,
} from 'vue';
import type { TestComponentProps } from './types';

const props = defineProps<TestComponentProps>();

const counter = ref(0);

watch(() => props.msg, () => {
  counter.value += 1;
}, {
  immediate: true,
});
</script>

<template>
  <div>{{ msg }}</div>
  <div>Changes: {{ counter }}</div>
</template>

```

**What did you expect to happen?**
No vue/no-undef-properties error thrown!

**What actually happened?**
ESLint: 'msg' is not defined.(vue/no-undef-properties)

**Repository to reproduce this issue**
https://github.com/tragid/vue-default-export-error

### PR DESCRIPTION
**Pull request by ota-meshi**
fixes #2183

---

This PR fixes unknown properties to be ignored from check when encountered.
There was a false positive if the user did not enable type information for rules in the ESLint configuration and defined the prop type externally.

### CODE REVIEW

File: lib/rules/no-undef-properties.js [hunk 1]
```diff
@@ -127,6 +127,8 @@ module.exports = {
 
         /** @type { Set<string | ASTNode> } */
         this.reported = new Set()
+
+        this.haveUnknownProperty = false
```
Comment (FloEdelmann) [inline lib/rules/no-undef-properties.js:131]: Should be `hasUnknownProperty`.

File: lib/rules/no-undef-properties.js [hunk 2]
```diff
@@ -206,6 +209,10 @@ module.exports = {
           }
         })
       }
+
+      markAsHaveUnknownProperty() {
```
Comment (FloEdelmann) [inline lib/rules/no-undef-properties.js:213]: Should be `markAsHasUnknownProperty`.

**Review by FloEdelmann — APPROVED** [review]
Apart from two minor wording mistakes, this looks good to me :)
