### PR TITLE
Fix 'no-shared-component-data' false positive when using arrow functions

### LINKED ISSUE #154: 'no-shared-component-data' false positive when using arrow functions
**Tell us about your environment**

* **ESLint Version:** 3.19.0
* **eslint-plugin-vue Version:** 3.11.0
* **Node Version:** 7.8.0

**Please show your full configuration:**

```
{
	root: true,
	extends: ['plugin:vue/recommended'],
	rules: {
		'vue/html-quotes': 'error',
		'vue/html-self-closing': ['error', {
			html: {
				normal: 'never',
				void: 'any',
				component: 'never'
			},
			svg: 'never',
			math: 'never'
		}],
		'vue/no-async-in-computed-properties': 'error',
		'vue/no-dupe-keys': 'error',
		'vue/no-duplicate-attributes': 'error',
		'vue/no-shared-component-data': 'error',
		'vue/order-in-components': 'error',
		'vue/v-bind-style': 'error',
		'vue/v-on-style': 'error'
	}
}
```

**What did you do? Please include the actual source code causing the issue.**

```vue
<script>
	export default {
		data: () => ({
			foo: 'bar'
		})
	};
</script>
```

**What did you expect to happen?**

No linting errors

**What actually happened? Please include the actual, raw output from ESLint.**

Error: `data` property in component must be a function

### PR DESCRIPTION
**Pull request by armano2**
fixes #154

### CODE REVIEW

File: tests/lib/rules/no-shared-component-data.js [hunk 1]
```diff
@@ -102,7 +105,18 @@ ruleTester.run('no-shared-component-data', rule, {
...
+    },
+    {
+      filename: 'test.vue',
+      code: `
+        export default {
+          data: () => {
+
+          }
+        }
+      `,
```
Comment (mysticatea) [inline tests/lib/rules/no-shared-component-data.js]: I suspect that this test case is not correct.
The filename is `.vue` and the code is in outside of `<script>` element.

Comment (michalsnik) [inline tests/lib/rules/no-shared-component-data.js]: This is sort of correct @mysticatea I think. This plugin doesn't transform `<script></script>` from a `vue` file. It's part of `eslint-vue-parser` responsibilities so here we expect that any code inside `script` tag will be accessible as usual. That's why we write this code directly without extra `script` tag. All we need to know in our rules is the extension of the file to detect if simple `export default` should be treated as component.

Comment (mysticatea) [inline tests/lib/rules/no-shared-component-data.js]: Ah, I was under the impression that `parserOptions` has `parser: "vue-eslint-parser"`. I'm sorry.
