### PR TITLE
fix(require-default-prop, require-valid-default-prop): resolve the property name

### LINKED ISSUE #776: vue/require-default-prop not picking up property name
**Tell us about your environment**	
* **ESLint version:**	5.12.0
* **eslint-plugin-vue version:** 5.1.0
* **Node version:**	8.11.4

**Please show your full configuration:**

```javascript
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    'standard',
    'plugin:vue/recommended'
  ],
  // required to lint *.vue files
  plugins: [
    'vue'
  ],
  // add your custom rules here
  rules: {
    'no-console':  process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',

    "no-multi-spaces": "off",
    "key-spacing": "off",
    "comma-dangle": ["warn", "always-multiline"],

    "vue/max-attributes-per-line": ["warn", {
      "singleline": 3,
      "multiline": {
        "max": 1,
        "allowFirstLine": false
      }
    }],
  },
  globals: {
    CORE_API_BASE_URL: false,
  },
}
```

**What did you do?**	

```vue
<script>
export default {
	props: {
	    tallStyle: Object,
	    'inverse': Boolean,
	    'actions': Array,
	}
}
</script>
```

**What did you expect to happen?**

The warnings should show the property names "tallStyle" and "actions"

**What actually happened?**

```
  95:5   warning  Prop 'tallStyle' requires default value to be set  vue/require-default-prop
  97:5   warning  Prop 'undefined' requires default value to be set  vue/require-default-prop
```

### PR DESCRIPTION
**Pull request by ota-meshi**
Fixed #776

### CODE REVIEW

File: lib/rules/require-default-prop.js [hunk 1]
```diff
@@ -141,11 +141,13 @@ module.exports = {
       const propsToReport = excludeBooleanProps(propsWithoutDefault)
 
       for (const prop of propsToReport) {
+        const propName = prop.propName != null ? prop.propName : `[${context.getSourceCode().getText(prop.key)}]`
```
Comment (michalsnik) [inline lib/rules/require-default-prop.js]: Why not `this.getStaticPropertyName(prop)`?

Comment (ota-meshi) [reply lib/rules/require-default-prop.js]: I have been using `getStaticPropertyName` in the following:
https://github.com/vuejs/eslint-plugin-vue/pull/791/files#diff-eae83c5838640e1c85538d8c9fbe35e3R489
