### PR TITLE
Fix: allow `v-on` without attribute values if it has verb modifiers (fixes #49)

### LINKED ISSUE #49: Suggestion: allow empty attribute value when event modifier is used
More specifically, only `stop` and `prevent` should be allowed.

**Tell us about your environment**

* **ESLint Version:** 4.0.0
* **eslint-plugin-vue Version:** 3.1.3
* **Node Version:** 8

**Please show your full configuration:**

Vanilla

**What did you do? Please include the actual source code causing the issue.**

```vue

<template>
<el-from @submit.native.prevent></el-form>
</template>
```

**What did you expect to happen?**

No error. Since this is illustrated in the official doc. https://vuejs.org/v2/guide/events.html#Event-Modifiers

**What actually happened? Please include the actual, raw output from ESLint.**

Error.  `'v-on' directives require that attribute value `.
https://github.com/octref/vetur/issues/279

### PR DESCRIPTION
**Pull request by mysticatea**
Fixes #49.

This PR fixes false positive of `no-invalid-v-on` rule.
If a `v-on` directive has verb modifiers (`.stop` or `.prevent`), now that rule allow the directive even if it does not have attribute values.

### CODE REVIEW

File: tests/lib/rules/no-invalid-v-on.js [hunk 1]
```diff
@@ -58,7 +62,7 @@ tester.run('no-invalid-v-on', rule, {
     {
       filename: 'test.vue',
       code: '<template><div v-on:click></div></template>',
-      errors: ["'v-on' directives require that attribute value."]
+      errors: ["'v-on' directives require that attribute value or verb modifiers."]
```
Comment (michalsnik) [inline tests/lib/rules/no-invalid-v-on.js]: Even though `@` is a simple alias I think it would be good idea to add more valid test examples with `v-on`, like e.g.:
```
<template><div v-on:click.prevent></div></template>
<template><div v-on:click.native.stop></div></template>
```

Comment (mysticatea) [inline tests/lib/rules/no-invalid-v-on.js]: I added those!

**Comment by michalsnik** [comment]
Released in `v3.3.0`
