### PR TITLE
Report `$set` and `$nextTick` in computed properties

### LINKED ISSUE #1744: no-side-effects-in-computed-properties does not report errors for this.$set or this.$nextTick
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.4.1
- **eslint-plugin-vue version:** 8.2.0
- **Node version:** 14.18.1
- **Operating System:** Ubuntu 18.04

**Please show your full configuration:**

```js
module.exports = {
  extends: [
    'plugin:vue/recommended',
  ],
}
```

**What did you do?**	

```vue
<script>
  export default {
    data: () => ({ bar: 1 }),
    computed: {
      foo: function () {
        this.$set(this, 'bar', 1);
        this.$nextTick(() => this.$set(this, 'bar', 2));
        return 1;
      }
    }
  };
</script>
```

**What did you expect to happen?**
Unexpected side effect in "foo" computed property  vue/no-side-effects-in-computed-properties for this.$set and this.$nextTick

**What actually happened?**

No reported errors

**Repository to reproduce this issue**

https://github.com/simonbrent/eslint-plugin-vue-bug

### PR DESCRIPTION
**Pull request by FloEdelmann**
Fixes #1744.

### CODE REVIEW

File: tests/lib/rules/no-side-effects-in-computed-properties.js [hunk 1]
```diff
@@ -446,6 +446,40 @@ ruleTester.run('no-side-effects-in-computed-properties', rule, {
...
     },
+    {
+      // https://github.com/vuejs/eslint-plugin-vue/issues/1744
+      code: `app.component('test', {
+        computed: {
+          fooBar() {
+            this.$set(this, 'foo', 'lorem');
+            Vue.set(this, 'bar', 'ipsum');
+
+            this.$nextTick(() => {});
```
Comment (ota-meshi) [inline tests/lib/rules/no-side-effects-in-computed-properties.js:457]: I think `nextTick` is an issue that should be reported in the `no-async-in-computed-properties` rule.

https://eslint.vuejs.org/rules/no-async-in-computed-properties.html

What do you think?

**Review by ota-meshi — CHANGES_REQUESTED** [review]

**Review by ota-meshi — APPROVED** [review]
LGTM!
