### PR TITLE
Fix false positives for script setup with ts literal type in `vue/require-valid-default-prop`

### LINKED ISSUE #1853: `vue/require-valid-default-prop` false-positive when using TS prop definition
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.5.0
- **eslint-plugin-vue version:** 8.2.0
- **Node version:** 14.17.0
- **Operating System:** macOS, Ubuntu 20

**Please show your full configuration:**

```json5
require("@rushstack/eslint-patch/modern-module-resolution");

module.exports = {
    root: true,
    extends: [
        "plugin:eslint-comments/recommended",
        "plugin:vue/vue3-strongly-recommended",
        "plugin:vue/vue3-recommended",
        "airbnb-typescript/base",
        "@vue/typescript/recommended",
        "@vue/prettier",
        "plugin:storybook/recommended",
        "plugin:markdown/recommended",
        "prettier",
    ],
    plugins: ["import"],
    parserOptions: {
        ecmaVersion: 2020,
        project: ["./tsconfig.json", "./tsconfig.vite-config.json"],
    },
    settings: {
        "import/parsers": {
            "@typescript-eslint/parser": [".ts", ".tsx"],
        },
    },
    env: {
        node: true,
        es2021: true,
        "vue/setup-compiler-macros": true,
    },
    rules: {
        "@typescript-eslint/quotes": ["error", "double", { allowTemplateLiterals: true, avoidEscape: true }],
        "max-len": ["error", 200, 4],
        "no-param-reassign": "off",
        "no-use-before-define": "off",
        "no-console": "error",
        "no-debugger": "error",
        "no-plusplus": "off",
        "@typescript-eslint/no-unused-vars": "error",
        "eslint-comments/disable-enable-pair": ["error", { allowWholeFile: true }],
        "vue/no-v-html": "error",
    },
    overrides: [
        {
            files: ["vite.config.ts", "tailwind.config.js"],
            rules: {
                "import/no-extraneous-dependencies": "off",
            },
        },
    ],
};
```

**What did you do?**	
```typescript
export interface SomePropInterface {
  someProp?: false | string;
}

withDefaults(defineProps<SomePropInterface>(), {
  someProp: false,
});
```

**What did you expect to happen?**

Assigning `false` to `someProp` as default value should be okay.

**What actually happened?**

`ESLint: Type of the default value for 'someProp' prop must be a string.(vue/require-valid-default-prop)`

**Repository to reproduce this issue**

I don't really think it's necessary but I will take the time to create one if really needed.

### PR DESCRIPTION
**Pull request by ota-meshi**
fixes #1853

### CODE REVIEW

File: tests/lib/rules/require-valid-default-prop.js [hunk 1]
```diff
@@ -252,6 +252,28 @@ ruleTester.run('require-valid-default-prop', rule, {
       parserOptions: { ecmaVersion: 6, sourceType: 'module' },
       parser: require.resolve('@typescript-eslint/parser'),
       errors: errorMessage('function')
+    },
+    {
+      filename: 'test.vue',
```
Comment (FloEdelmann) [inline tests/lib/rules/require-valid-default-prop.js:257]: Maybe add a reference to https://github.com/vuejs/eslint-plugin-vue/issues/1853 here:

```suggestion
      // https://github.com/vuejs/eslint-plugin-vue/issues/1853
      filename: 'test.vue',
```

**Review by FloEdelmann — APPROVED** [review]
Looks good :)
