### PR TITLE
[Fix] Incorrect errors in invalid EOF cases (fixes #268)

### LINKED ISSUE #268: `vue/html-end-tags` rule goes out of control
**Tell us about your environment**

* **ESLint Version:** 4.12.1
* **eslint-plugin-vue Version:** 4.0.0-beta.0

**Please show your full configuration:**
**What did you do? Please include the actual source code causing the issue.**

See [playground](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwidGVzdD5IZWxsbyE8L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJydWxlcyI6eyJ2dWUvaHRtbC1lbmQtdGFncyI6MiwidnVlL25vLXBhcnNpbmctZXJyb3IiOjJ9fQ==).

**What did you expect to happen?**

Autofix does not change the code.

**What actually happened? Please include the actual, raw output from ESLint.**

The autofix of `vue/html-end-tags` added many `</template>` tags.
The rule should do nothing if an `eof-in-tag` error exists.

### PR DESCRIPTION
**Pull request by mysticatea**
This PR fixes #268 and some similar cases:

- [Case 1](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PjwhLS1cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwicnVsZXMiOnsidnVlL2h0bWwtZW5kLXRhZ3MiOjIsInZ1ZS9uby1wYXJzaW5nLWVycm9yIjoyfX0=)
- [Case 2](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxzdmc+XG4gICAgICA8IVtDREFUQVt0ZXN0XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsInJ1bGVzIjp7InZ1ZS9odG1sLWVuZC10YWdzIjoyLCJ2dWUvbm8tcGFyc2luZy1lcnJvciI6Mn19)
- [Case 3](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDwhLS1cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwicnVsZXMiOnsidnVlL2h0bWwtZW5kLXRhZ3MiOjIsInZ1ZS9uby1wYXJzaW5nLWVycm9yIjoyfX0=)
- [Case 4](https://mysticatea.github.io/vue-eslint-demo/#eyJjb2RlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDwhLS1cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwicnVsZXMiOnsidnVlL2h0bWwtc2VsZi1jbG9zaW5nIjoyLCJ2dWUvbm8tcGFyc2luZy1lcnJvciI6Mn19)

I.e. some rules are confused in invalid EOF. This PR fixes some rules to not report errors if the code has invalid EOF.

### CODE REVIEW

File: tests/lib/rules/html-end-tags.js [hunk 1]
```diff
@@ -54,27 +54,21 @@ tester.run('html-end-tags', rule, {
...
-    //   code: '<template><div><img></img></div></template>',
-    //   output: '<template><div><img></template>',
-    //   errors: ["'<img>' should not have end tag."]
-    // },
-    // {
-    //   filename: 'test.vue',
-    //   code: '<template><div><input></input></div></template>',
-    //   output: '<template><div><input></template>',
-    //   errors: ["'<input>' should not have end tag."]
-    // },
```
Comment (mysticatea) [inline tests/lib/rules/html-end-tags.js]: Those tests are no longer needed. It's a kind of syntax error if void elements have their end tag, so it's reported by `vue/no-parsing-error` rule.

Comment (michalsnik) [reply tests/lib/rules/html-end-tags.js]: Okay, then please remove it :)

**Comment by michalsnik** [comment]
Please remove those commented lines and we're good to merge it. Good work!

File: tests/lib/rules/html-end-tags.js (hunk 1 above)
Comment (mysticatea) [reply tests/lib/rules/html-end-tags.js]: It has been removed already 😀

Comment (michalsnik) [reply tests/lib/rules/html-end-tags.js]: Apparently I need to start wearing glasses 🤓
